### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by toolapcblack** [danielvijge/lms_mixcloud#30]
Tried uninstalling then was going to re-install, as a last resort to get it working, but no longer showing under 3rd party plugins either! 
Contacted Daniel and he said "As MixCloud doesn’t have a public API to play track, this plugin uses https://www.dlmixcloud.com/ to get a playable download URL. However, this service seems to have stopped working. So therefore this plugin also no longer works."

**Comment by danielvijge** [comment]
There's a very rough implementation available in https://github.com/danielvijge/lms_mixcloud/pull/31 I haven't done any real testing yet. And I don't know locoloader at all, so no idea how stable this service is for getting the MixCloud stream URL.

**Comment by danielvijge** [comment]
locoloader has a rate limit of 2 requests per 6 hours, so I reworked it again with savelink.info as a service in #32 Initially it starts playing, but the stream stops after about 1:20. In the browser this same URL plays OK, so it might not be an issue with the MixCloud plugins.

**Comment by danielvijge** [comment]
initial test is OK, but you need to set in Settings: Advanced -> Network -> Streaming mode for HTTP(S) set to "Persistent mode".

**Comment by danielvijge** [comment]
A (possible) fix has been merged in 0b5fe31240da294d4d204dc8a80738259582a8b0 and will be available as beta build 0.9.3. The comment about the change to the streaming mode is no longer needed, as the streaming mode is set automatically by the MixCloud plugin.

**Comment by toolapcblack** [comment]
many thanks It looks like the plugin is not available for those running VortexBox SW Version: 2.4  Logitech Media Server Version: 7.9.1 - 0.7.20180404git1522249619 @ Mon May 14 10:51:59 EDT 2018
 any way to easy upgrade to a newer version?

    On Monday, 18 September 2023 at 23:19:55 BST, Daniel Vijge ***@***.***> wrote:  
 
 


A (possible) fix has been merged in 0b5fe31 and will be available as beta build 0.9.3. The comment about the change to the streaming mode is no longer needed, as the streaming mode is set automatically by the MixCloud plugin.

**Comment by danielvijge** [comment]
I'm not familiar with VortexBox, but if it's running LMS version 7.9.1 -- that's quite old, as it was released in April 2018. Since the release of the Mixcloud plugin 0.5 (from April 2021) the minimum required version of LMS is 8.1. For this new release (0.10) it is bumped to 8.2.
So you would have to see if you can upgrade your LMS version to 8.2 or newer.

(technically you can also try to modify the plugin code and lower the minimum version, but I have no idea if it works or not. I always run the latest nightly version on LMS and test my plugins on that)
